#!/bin/bash

# Before/After Slider
cat > templates/modal/before-after-slider/iam-modal_before_after_slider_v1.html << 'EOF'
<!doctype html>
<html><head><meta charset="UTF-8"><style>*{margin:0;padding:0}body{font-family:sans-serif;overflow:hidden}#overlay{position:fixed;inset:0;background:rgba(0,0,0,.75);display:flex;align-items:center;justify-content:center;z-index:9999}.modal{background:#fff;border-radius:20px;max-width:400px;width:90%;padding:30px 20px;text-align:center}.title{font-size:20px;font-weight:700;margin-bottom:20px}.slider-container{position:relative;width:100%;height:300px;overflow:hidden;border-radius:12px}.before,.after{position:absolute;top:0;left:0;width:100%;height:100%;background-size:cover;background-position:center}.before{background-image:url('https://picsum.photos/400/300?random=1')}.after{background-image:url('https://picsum.photos/400/300?random=2');clip-path:inset(0 50% 0 0)}.handle{position:absolute;top:0;left:50%;width:4px;height:100%;background:#fff;cursor:ew-resize;z-index:10}.label{position:absolute;top:10px;padding:8px 12px;background:rgba(0,0,0,.7);color:#fff;border-radius:6px;font-size:12px}.before-label{left:10px}.after-label{right:10px}</style></head><body><div id="overlay"><div class="modal"><div class="title">Before & After</div><div class="slider-container" id="container"><div class="before"></div><div class="after" id="after"></div><div class="handle" id="handle"></div><span class="label before-label">Before</span><span class="label after-label">After</span></div></div></div><script>var container=document.getElementById("container");var handle=document.getElementById("handle");var after=document.getElementById("after");var isDragging=false;handle.onmousedown=function(){isDragging=true};document.onmousemove=function(e){if(!isDragging)return;var rect=container.getBoundingClientRect();var x=e.clientX-rect.left;var percent=(x/rect.width)*100;if(percent<0)percent=0;if(percent>100)percent=100;handle.style.left=percent+"%";after.style.clipPath="inset(0 "+(100-percent)+"% 0 0)"};document.onmouseup=function(){isDragging=false};window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("before_after_viewed")}catch(e){}},false)</script></body></html>
EOF

echo "# Before/After Slider Template
비포/애프터 이미지 슬라이더. 드래그로 이미지 비교." > templates/modal/before-after-slider/README.md

# Image Hotspot
cat > templates/modal/image-hotspot/iam-modal_image_hotspot_v1.html << 'EOF'
<!doctype html>
<html><head><meta charset="UTF-8"><style>*{margin:0;padding:0}body{font-family:sans-serif;overflow:hidden}#overlay{position:fixed;inset:0;background:rgba(0,0,0,.75);display:flex;align-items:center;justify-content:center;z-index:9999}.modal{background:#fff;border-radius:20px;max-width:450px;width:90%;padding:20px}.image-container{position:relative;width:100%;height:400px;background:url('https://picsum.photos/450/400?random=1') center/cover;border-radius:12px}.hotspot{position:absolute;width:40px;height:40px;background:#667eea;border-radius:50%;border:3px solid #fff;cursor:pointer;animation:pulse 2s infinite;display:flex;align-items:center;justify-content:center;color:#fff;font-weight:700;box-shadow:0 2px 10px rgba(0,0,0,.3)}.tooltip{display:none;position:absolute;bottom:50px;left:50%;transform:translateX(-50%);background:#fff;padding:12px 16px;border-radius:8px;box-shadow:0 4px 12px rgba(0,0,0,.2);white-space:nowrap;font-size:14px}.hotspot:hover .tooltip{display:block}@keyframes pulse{0%,100%{transform:scale(1)}50%{transform:scale(1.1)}}</style></head><body><div id="overlay"><div class="modal"><div class="image-container"><div class="hotspot" style="top:30%;left:20%">1<div class="tooltip">포인트 1: 설명</div></div><div class="hotspot" style="top:50%;left:60%">2<div class="tooltip">포인트 2: 설명</div></div><div class="hotspot" style="top:70%;left:40%">3<div class="tooltip">포인트 3: 설명</div></div></div></div></div><script>window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("image_hotspot_viewed")}catch(e){}},false);document.querySelectorAll(".hotspot").forEach(function(h){h.onclick=function(){window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logClick("hotspot_"+this.textContent)}catch(e){}},false)}})</script></body></html>
EOF

echo "# Image Hotspot Template
이미지 핫스팟 템플릿. 클릭 가능한 포인트, 툴팁 표시." > templates/modal/image-hotspot/README.md

# Progress Bar
cat > templates/modal/progress-bar/iam-modal_progress_bar_v1.html << 'EOF'
<!doctype html>
<html><head><meta charset="UTF-8"><style>*{margin:0;padding:0}body{font-family:sans-serif;overflow:hidden}#overlay{position:fixed;inset:0;background:rgba(0,0,0,.75);display:flex;align-items:center;justify-content:center;z-index:9999}.modal{background:#fff;border-radius:20px;max-width:400px;width:90%;padding:30px 20px;text-align:center}.title{font-size:20px;font-weight:700;margin-bottom:10px}.desc{font-size:14px;color:#666;margin-bottom:25px}.progress-container{margin:20px 0}.progress-label{display:flex;justify-content:space-between;font-size:14px;margin-bottom:10px}.progress-bar{width:100%;height:30px;background:#f0f0f0;border-radius:15px;overflow:hidden;position:relative}.progress-fill{height:100%;background:linear-gradient(90deg,#667eea,#764ba2);transition:width 1s ease;display:flex;align-items:center;justify-content:center;color:#fff;font-weight:600;font-size:14px}.milestone{margin:20px 0;padding:15px;background:#f9f9f9;border-radius:10px;text-align:left}.milestone-title{font-weight:600;margin-bottom:5px}.milestone-reward{color:#667eea;font-weight:600}.btn{width:100%;padding:14px;background:#667eea;color:#fff;border:none;border-radius:8px;cursor:pointer;font-size:15px;font-weight:600;margin-top:15px}</style></head><body><div id="overlay"><div class="modal"><div class="title">🎯 목표 달성 진행률</div><div class="desc">목표를 달성하고 리워드를 받으세요!</div><div class="progress-container"><div class="progress-label"><span>현재 진행률</span><span id="percent">60%</span></div><div class="progress-bar"><div class="progress-fill" id="fill" style="width:0%">60%</div></div></div><div class="milestone"><div class="milestone-title">✅ 50% 달성 - 완료!</div><div class="milestone-reward">보상: 1,000P 지급 완료</div></div><div class="milestone"><div class="milestone-title">🎯 100% 달성 시</div><div class="milestone-reward">보상: 10,000P + 특별 쿠폰</div></div><button class="btn">계속 진행하기</button></div></div><script>setTimeout(function(){document.getElementById("fill").style.width="60%"},300);window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("progress_bar_viewed",{progress:60})}catch(e){}},false)</script></body></html>
EOF

echo "# Progress Bar Template
진행률 표시 템플릿. 목표 달성 진행률, 마일스톤 리워드." > templates/modal/progress-bar/README.md

# Social Proof
cat > templates/modal/social-proof/iam-modal_social_proof_v1.html << 'EOF'
<!doctype html>
<html><head><meta charset="UTF-8"><style>*{margin:0;padding:0}body{font-family:sans-serif;overflow:hidden}#overlay{position:fixed;inset:0;background:rgba(0,0,0,.75);display:flex;align-items:center;justify-content:center;z-index:9999}.modal{background:#fff;border-radius:20px;max-width:380px;width:90%;padding:30px 20px}.title{font-size:20px;font-weight:700;margin-bottom:20px;text-align:center}.activity{padding:15px;background:#f9f9f9;border-radius:10px;margin-bottom:12px;display:flex;align-items:center;gap:12px}.avatar{width:40px;height:40px;border-radius:50%;background:#667eea;color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:14px}.activity-text{flex:1;font-size:14px;line-height:1.4}.activity-time{font-size:12px;color:#999}.stats{margin-top:20px;padding:20px;background:linear-gradient(135deg,#667eea,#764ba2);border-radius:12px;color:#fff;text-align:center}.stat-value{font-size:36px;font-weight:700;margin-bottom:5px}.stat-label{font-size:14px;opacity:.9}.btn{width:100%;padding:14px;background:#4caf50;color:#fff;border:none;border-radius:8px;cursor:pointer;font-size:15px;font-weight:600;margin-top:15px}</style></head><body><div id="overlay"><div class="modal"><div class="title">🔥 실시간 활동</div><div class="activity"><div class="avatar">KM</div><div><div class="activity-text"><strong>김민수</strong>님이 VIP 멤버십 가입</div><div class="activity-time">방금 전</div></div></div><div class="activity"><div class="avatar">PJ</div><div><div class="activity-text"><strong>박지은</strong>님이 50,000P 적립</div><div class="activity-time">2분 전</div></div></div><div class="activity"><div class="avatar">LY</div><div><div class="activity-text"><strong>이유진</strong>님이 친구 5명 초대</div><div class="activity-time">5분 전</div></div></div><div class="stats"><div class="stat-value">1,247</div><div class="stat-label">오늘 가입한 회원</div></div><button class="btn">나도 참여하기</button></div></div><script>window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("social_proof_viewed")}catch(e){}},false)</script></body></html>
EOF

echo "# Social Proof Template
소셜 프루프 알림 템플릿. 실시간 활동, 통계, 참여 유도." > templates/modal/social-proof/README.md

echo "Created Phase 4 & 5 templates"
