#!/bin/bash

# Shake to Reveal
cat > templates/modal/shake-reveal/iam-modal_shake_reveal_v1.html << 'EOF'
<!doctype html>
<html><head><meta charset="UTF-8"><style>*{margin:0;padding:0}body{font-family:sans-serif;overflow:hidden}#overlay{position:fixed;inset:0;background:rgba(0,0,0,.75);display:flex;align-items:center;justify-content:center;z-index:9999}.modal{background:#fff;border-radius:20px;max-width:350px;width:90%;padding:40px 20px;text-align:center}.title{font-size:22px;font-weight:700;margin-bottom:15px}.shake-box{width:200px;height:200px;background:linear-gradient(135deg,#667eea,#764ba2);margin:20px auto;border-radius:20px;display:flex;align-items:center;justify-content:center;font-size:64px;cursor:pointer;transition:transform .1s}.shake-box.shaking{animation:shake .5s}.prize{font-size:48px;margin:20px 0;display:none}.prize.show{display:block}@keyframes shake{0%,100%{transform:translateX(0)}25%{transform:translateX(-10px) rotate(-5deg)}75%{transform:translateX(10px) rotate(5deg)}}</style></head><body><div id="overlay"><div class="modal"><div class="title">📦 흔들어서 선물 받기!</div><div class="shake-box" id="box">🎁</div><div class="prize" id="prize"></div></div></div><script>var box=document.getElementById("box");var prize=document.getElementById("prize");var shakes=0;var prizes=["🎉 10,000P","💎 20,000P","🏆 5,000P"];box.onclick=function(){box.classList.add("shaking");shakes++;setTimeout(function(){box.classList.remove("shaking")},500);if(shakes>=3){var p=prizes[Math.floor(Math.random()*prizes.length)];prize.textContent=p;prize.classList.add("show");box.style.display="none";window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("shake_reveal_complete")}catch(e){}},false)}};window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("shake_reveal_viewed")}catch(e){}},false)</script></body></html>
EOF

echo "# Shake to Reveal Template
흔들기 제스처로 프라이즈 공개. 모바일 인터랙티브 게임화." > templates/modal/shake-reveal/README.md

# Gift Box
cat > templates/modal/gift-box/iam-modal_gift_box_v1.html << 'EOF'
<!doctype html>
<html><head><meta charset="UTF-8"><style>*{margin:0;padding:0}body{font-family:sans-serif;overflow:hidden}#overlay{position:fixed;inset:0;background:rgba(0,0,0,.75);display:flex;align-items:center;justify-content:center;z-index:9999}.modal{background:#fff;border-radius:20px;max-width:380px;width:90%;padding:30px 20px;text-align:center}.title{font-size:22px;font-weight:700;margin-bottom:20px}.boxes{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin:20px 0}.box{aspect-ratio:1;background:linear-gradient(135deg,#f093fb,#f5576c);border-radius:15px;display:flex;align-items:center;justify-content:center;font-size:48px;cursor:pointer;transition:transform .2s}.box:hover{transform:scale(1.05)}.result{margin-top:20px;font-size:20px;font-weight:600;display:none}.result.show{display:block}</style></head><body><div id="overlay"><div class="modal"><div class="title">🎁 선물 상자를 선택하세요!</div><div class="boxes" id="boxes"></div><div class="result" id="result"></div></div></div><script>var prizes=["💎 50,000P","🏆 10,000P","🎉 5,000P","⭐ 다시 도전","💰 20,000P","🎁 30,000P"];var boxes=document.getElementById("boxes");var result=document.getElementById("result");for(var i=0;i<6;i++){var box=document.createElement("div");box.className="box";box.textContent="🎁";box.onclick=function(){var p=prizes[Math.floor(Math.random()*prizes.length)];result.textContent=p;result.classList.add("show");boxes.style.display="none";window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("gift_box_opened")}catch(e){}},false)};boxes.appendChild(box)}window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("gift_box_viewed")}catch(e){}},false)</script></body></html>
EOF

echo "# Gift Box Template
선물 상자 선택 게임. 6개 박스 중 하나 선택, 랜덤 프라이즈." > templates/modal/gift-box/README.md

# Multi-Step Form
cat > templates/modal/multi-step-form/iam-modal_multi_step_form_v1.html << 'EOF'
<!doctype html>
<html><head><meta charset="UTF-8"><style>*{margin:0;padding:0}body{font-family:sans-serif;overflow:hidden}#overlay{position:fixed;inset:0;background:rgba(0,0,0,.75);display:flex;align-items:center;justify-content:center;z-index:9999}.modal{background:#fff;border-radius:20px;max-width:400px;width:90%;padding:30px 20px}.step{display:none}.step.active{display:block}.progress{height:8px;background:#f0f0f0;border-radius:4px;margin-bottom:20px}.progress-fill{height:100%;background:#667eea;border-radius:4px;transition:width .3s}.title{font-size:20px;font-weight:700;margin-bottom:15px}input,select{width:100%;padding:12px;border:1px solid #ddd;border-radius:8px;margin-bottom:15px;font-size:14px}.btn{width:100%;padding:14px;background:#667eea;color:#fff;border:none;border-radius:8px;cursor:pointer;font-size:15px;font-weight:600}</style></head><body><div id="overlay"><div class="modal"><div class="progress"><div class="progress-fill" id="progress" style="width:33%"></div></div><div class="step active" id="step1"><div class="title">1/3: 기본 정보</div><input type="text" placeholder="이름" id="name"><input type="email" placeholder="이메일" id="email"><button class="btn" onclick="nextStep(2)">다음</button></div><div class="step" id="step2"><div class="title">2/3: 선호도</div><select id="category"><option>카테고리 선택</option><option>패션</option><option>뷰티</option><option>테크</option></select><button class="btn" onclick="nextStep(3)">다음</button></div><div class="step" id="step3"><div class="title">3/3: 완료</div><p style="margin-bottom:15px">감사합니다! 500P가 적립되었습니다.</p><button class="btn" onclick="submit()">완료</button></div></div></div><script>function nextStep(n){document.querySelectorAll(".step").forEach(function(s){s.classList.remove("active")});document.getElementById("step"+n).classList.add("active");document.getElementById("progress").style.width=(n*33)+"%"}function submit(){window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("form_submitted");brazeBridge.closeMessage()}catch(e){}},false)}window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("form_viewed")}catch(e){}},false)</script></body></html>
EOF

echo "# Multi-Step Form Template
다단계 폼 템플릿. 3단계 입력, 진행률 표시, 데이터 수집." > templates/modal/multi-step-form/README.md

# Star Rating
cat > templates/modal/star-rating/iam-modal_star_rating_v1.html << 'EOF'
<!doctype html>
<html><head><meta charset="UTF-8"><style>*{margin:0;padding:0}body{font-family:sans-serif;overflow:hidden}#overlay{position:fixed;inset:0;background:rgba(0,0,0,.75);display:flex;align-items:center;justify-content:center;z-index:9999}.modal{background:#fff;border-radius:20px;max-width:380px;width:90%;padding:30px 20px;text-align:center}.title{font-size:22px;font-weight:700;margin-bottom:10px}.desc{font-size:14px;color:#666;margin-bottom:25px}.stars{display:flex;justify-content:center;gap:10px;margin-bottom:20px}.star{font-size:48px;cursor:pointer;transition:transform .2s}.star:hover{transform:scale(1.2)}.star.active{color:#ffd700}textarea{width:100%;padding:12px;border:1px solid #ddd;border-radius:8px;margin-bottom:15px;font-family:sans-serif;font-size:14px;resize:vertical}.btn{width:100%;padding:14px;background:#667eea;color:#fff;border:none;border-radius:8px;cursor:pointer;font-size:15px;font-weight:600}</style></head><body><div id="overlay"><div class="modal"><div class="title">⭐ 앱 평가하기</div><div class="desc">서비스 경험을 알려주세요</div><div class="stars" id="stars"></div><textarea id="feedback" placeholder="상세한 의견을 남겨주세요 (선택)" rows="4"></textarea><button class="btn" onclick="submit()">제출</button></div></div><script>var rating=0;var stars=document.getElementById("stars");for(var i=1;i<=5;i++){var star=document.createElement("span");star.className="star";star.textContent="★";star.dataset.rating=i;star.onclick=function(){rating=parseInt(this.dataset.rating);document.querySelectorAll(".star").forEach(function(s,idx){s.classList.toggle("active",idx<rating)})};stars.appendChild(star)}function submit(){if(rating===0){alert("별점을 선택해주세요");return}window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("rating_submitted",{rating:rating,feedback:document.getElementById("feedback").value});brazeBridge.getUser().setCustomUserAttribute("app_rating",rating);brazeBridge.closeMessage()}catch(e){}},false)}window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("rating_viewed")}catch(e){}},false)</script></body></html>
EOF

echo "# Star Rating Template
별점 평가 템플릿. 5점 만점 별점 + 피드백 텍스트 입력." > templates/modal/star-rating/README.md

echo "Created Phase 2 & 3 templates"
