#!/bin/bash

# App Permission Request
cat > templates/modal/app-permission/iam-modal_app_permission_v1.html << 'EOF'
<!doctype html>
<html><head><meta charset="UTF-8"><style>*{margin:0;padding:0}body{font-family:sans-serif;overflow:hidden}#overlay{position:fixed;inset:0;background:rgba(0,0,0,.75);display:flex;align-items:center;justify-content:center;z-index:9999}.modal{background:#fff;border-radius:20px;max-width:380px;width:90%;padding:30px 20px;text-align:center}.icon{font-size:64px;margin-bottom:15px}.title{font-size:22px;font-weight:700;margin-bottom:10px}.desc{font-size:14px;color:#666;line-height:1.6;margin-bottom:25px}.benefits{text-align:left;margin:20px 0}.benefit{display:flex;align-items:start;gap:10px;margin-bottom:12px}.benefit-icon{font-size:20px;margin-top:2px}.benefit-text{font-size:14px;line-height:1.4}.btn{width:100%;padding:16px;background:#667eea;color:#fff;border:none;border-radius:10px;cursor:pointer;font-size:16px;font-weight:600;margin-bottom:10px}.btn-secondary{background:#f0f0f0;color:#666}</style></head><body><div id="overlay"><div class="modal"><div class="icon">🔔</div><div class="title">푸시 알림 받기</div><div class="desc">중요한 업데이트와 특별 혜택을 놓치지 마세요</div><div class="benefits"><div class="benefit"><div class="benefit-icon">✅</div><div class="benefit-text">한정 세일 및 특가 정보 실시간 알림</div></div><div class="benefit"><div class="benefit-icon">✅</div><div class="benefit-text">맞춤형 상품 추천</div></div><div class="benefit"><div class="benefit-icon">✅</div><div class="benefit-text">주문 배송 현황 실시간 업데이트</div></div></div><button class="btn" onclick="allow()">알림 받기</button><button class="btn btn-secondary" onclick="later()">나중에</button></div></div><script>function allow(){window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.requestPushPermission(function(){brazeBridge.logCustomEvent("push_permission_granted")},function(){brazeBridge.logCustomEvent("push_permission_denied")});brazeBridge.closeMessage()}catch(e){}},false)}function later(){window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("push_permission_later");brazeBridge.closeMessage()}catch(e){}},false)}window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("push_permission_viewed")}catch(e){}},false)</script></body></html>
EOF

echo "# App Permission Request Template
앱 권한 요청 템플릿. 푸시 알림, 위치, 카메라 등 권한 요청." > templates/modal/app-permission/README.md

# Feature Tour
cat > templates/modal/feature-tour/iam-modal_feature_tour_v1.html << 'EOF'
<!doctype html>
<html><head><meta charset="UTF-8"><style>*{margin:0;padding:0}body{font-family:sans-serif;overflow:hidden}#overlay{position:fixed;inset:0;background:rgba(0,0,0,.75);display:flex;align-items:center;justify-content:center;z-index:9999}.modal{background:#fff;border-radius:20px;max-width:400px;width:90%;padding:30px 20px;text-align:center}.slide{display:none}.slide.active{display:block}.illustration{font-size:80px;margin-bottom:20px}.title{font-size:22px;font-weight:700;margin-bottom:12px}.desc{font-size:15px;color:#666;line-height:1.6;margin-bottom:25px}.dots{display:flex;justify-content:center;gap:8px;margin:20px 0}.dot{width:8px;height:8px;border-radius:50%;background:#ddd;transition:all .3s}.dot.active{width:24px;border-radius:4px;background:#667eea}.btn{width:100%;padding:16px;background:#667eea;color:#fff;border:none;border-radius:10px;cursor:pointer;font-size:16px;font-weight:600}.skip{margin-top:10px;color:#999;font-size:14px;cursor:pointer}</style></head><body><div id="overlay"><div class="modal"><div class="slide active"><div class="illustration">🎯</div><div class="title">맞춤형 추천</div><div class="desc">AI가 분석한 당신만을 위한 상품 추천</div></div><div class="slide"><div class="illustration">💎</div><div class="title">포인트 적립</div><div class="desc">구매할 때마다 5% 포인트 자동 적립</div></div><div class="slide"><div class="illustration">🚀</div><div class="title">빠른 배송</div><div class="desc">오늘 주문하면 내일 도착하는 익일 배송</div></div><div class="dots"><span class="dot active"></span><span class="dot"></span><span class="dot"></span></div><button class="btn" onclick="next()">다음</button><div class="skip" onclick="skip()">건너뛰기</div></div></div><script>var current=0;var slides=document.querySelectorAll(".slide");var dots=document.querySelectorAll(".dot");function next(){current++;if(current>=slides.length){window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("feature_tour_completed");brazeBridge.closeMessage()}catch(e){}},false);return}updateSlide()}function updateSlide(){slides.forEach(function(s,i){s.classList.toggle("active",i===current)});dots.forEach(function(d,i){d.classList.toggle("active",i===current)})}function skip(){window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("feature_tour_skipped");brazeBridge.closeMessage()}catch(e){}},false)}window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("feature_tour_viewed")}catch(e){}},false)</script></body></html>
EOF

echo "# Feature Tour Template
기능 투어 템플릿. 3단계 온보딩, 스와이프 네비게이션." > templates/modal/feature-tour/README.md

# Personality Quiz
cat > templates/modal/personality-quiz/iam-modal_personality_quiz_v1.html << 'EOF'
<!doctype html>
<html><head><meta charset="UTF-8"><style>*{margin:0;padding:0}body{font-family:sans-serif;overflow:hidden}#overlay{position:fixed;inset:0;background:rgba(0,0,0,.75);display:flex;align-items:center;justify-content:center;z-index:9999}.modal{background:#fff;border-radius:20px;max-width:400px;width:90%;padding:30px 20px}.question{display:none}.question.active{display:block}.title{font-size:20px;font-weight:700;margin-bottom:20px;text-align:center}.options{display:flex;flex-direction:column;gap:12px}.option{padding:16px;background:#f9f9f9;border:2px solid transparent;border-radius:10px;cursor:pointer;transition:all .2s;text-align:center;font-size:15px}.option:hover{background:#f0f0f0;border-color:#667eea}.result{display:none;text-align:center}.result.show{display:block}.result-icon{font-size:64px;margin-bottom:15px}.result-title{font-size:22px;font-weight:700;margin-bottom:10px}.result-desc{font-size:15px;color:#666;line-height:1.6;margin-bottom:20px}.btn{width:100%;padding:14px;background:#667eea;color:#fff;border:none;border-radius:8px;cursor:pointer;font-size:15px;font-weight:600}</style></head><body><div id="overlay"><div class="modal"><div class="question active" id="q1"><div class="title">Q1. 쇼핑 스타일은?</div><div class="options"><div class="option" onclick="answer(1,'A')">계획적으로 필요한 것만 구매</div><div class="option" onclick="answer(1,'B')">트렌드 중심의 즉흥 구매</div><div class="option" onclick="answer(1,'C')">할인/특가 위주 구매</div></div></div><div class="question" id="q2"><div class="title">Q2. 선호하는 카테고리는?</div><div class="options"><div class="option" onclick="answer(2,'A')">패션/뷰티</div><div class="option" onclick="answer(2,'B')">테크/가전</div><div class="option" onclick="answer(2,'C')">리빙/인테리어</div></div></div><div class="result" id="result"><div class="result-icon">🎯</div><div class="result-title">맞춤형 쇼퍼</div><div class="result-desc">트렌드를 선도하는 스마트한 쇼핑 스타일! 당신을 위한 특별 쿠폰을 준비했어요.</div><button class="btn" onclick="claim()">쿠폰 받기</button></div></div></div><script>var answers=[];function answer(q,a){answers.push(a);document.querySelectorAll(".question").forEach(function(el){el.classList.remove("active")});if(q===1){document.getElementById("q2").classList.add("active")}else{showResult()}}function showResult(){document.getElementById("result").classList.add("show");window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("quiz_completed",{answers:answers.join(",")});brazeBridge.getUser().setCustomUserAttribute("shopping_type","trendy_shopper")}catch(e){}},false)}function claim(){window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("quiz_coupon_claimed");brazeBridge.closeMessage()}catch(e){}},false)}window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("quiz_viewed")}catch(e){}},false)</script></body></html>
EOF

echo "# Personality Quiz Template
성격 퀴즈 템플릿. 2단계 질문, 결과 분석, 맞춤 추천." > templates/modal/personality-quiz/README.md

# Swipe Cards
cat > templates/modal/swipe-cards/iam-modal_swipe_cards_v1.html << 'EOF'
<!doctype html>
<html><head><meta charset="UTF-8"><style>*{margin:0;padding:0}body{font-family:sans-serif;overflow:hidden}#overlay{position:fixed;inset:0;background:rgba(0,0,0,.75);display:flex;align-items:center;justify-content:center;z-index:9999}.modal{background:#fff;border-radius:20px;max-width:400px;width:90%;padding:30px 20px;text-align:center}.title{font-size:20px;font-weight:700;margin-bottom:20px}.cards-container{position:relative;height:350px;margin:20px 0}.card{position:absolute;width:100%;background:#fff;border-radius:16px;box-shadow:0 4px 20px rgba(0,0,0,.1);padding:20px;cursor:grab;transition:transform .3s;top:0;left:0}.card.hidden{display:none}.card-image{width:100%;height:200px;background:#f0f0f0;border-radius:12px;margin-bottom:15px;background-size:cover;background-position:center}.card-title{font-size:18px;font-weight:700;margin-bottom:8px}.card-price{font-size:16px;color:#667eea;font-weight:600}.actions{display:flex;gap:15px;justify-content:center;margin-top:20px}.action-btn{width:60px;height:60px;border-radius:50%;border:none;cursor:pointer;font-size:28px;display:flex;align-items:center;justify-content:center;box-shadow:0 2px 10px rgba(0,0,0,.1)}.like{background:#4caf50;color:#fff}.dislike{background:#f44336;color:#fff}</style></head><body><div id="overlay"><div class="modal"><div class="title">관심 상품을 선택하세요</div><div class="cards-container" id="cards"><div class="card"><div class="card-image" style="background-image:url('https://picsum.photos/300/200?random=1')"></div><div class="card-title">프리미엄 상품 1</div><div class="card-price">99,000원</div></div><div class="card hidden"><div class="card-image" style="background-image:url('https://picsum.photos/300/200?random=2')"></div><div class="card-title">프리미엄 상품 2</div><div class="card-price">129,000원</div></div><div class="card hidden"><div class="card-image" style="background-image:url('https://picsum.photos/300/200?random=3')"></div><div class="card-title">프리미엄 상품 3</div><div class="card-price">159,000원</div></div></div><div class="actions"><button class="action-btn dislike" onclick="swipe('dislike')">✕</button><button class="action-btn like" onclick="swipe('like')">♥</button></div></div></div><script>var cards=document.querySelectorAll(".card");var current=0;function swipe(action){if(current>=cards.length)return;cards[current].classList.add("hidden");window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("card_swiped",{action:action,card:current+1})}catch(e){}},false);current++;if(current<cards.length){cards[current].classList.remove("hidden")}else{window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("swipe_cards_completed");brazeBridge.closeMessage()}catch(e){}},false)}}window.addEventListener("ab.BridgeReady",function(){try{brazeBridge.logCustomEvent("swipe_cards_viewed")}catch(e){}},false)</script></body></html>
EOF

echo "# Swipe Cards Template
스와이프 카드 템플릿. 좌우 스와이프, 상품 선호도 수집." > templates/modal/swipe-cards/README.md

echo "Created Phase 6-8 templates - ALL 18 TEMPLATES COMPLETE!"
